### PR TITLE
Update to v1.1.6

### PR DESCRIPTION
**Pull request by benjamreis**

### CODE REVIEW

**Comment by benjamreis** [comment]
[Koji scratch build v8.3-incoming](https://koji.xcp-ng.org/taskinfo?taskID=34578)

**Comment by benjamreis** [comment]
Waiting for more recent XAPI.

**Review by gduperrey — APPROVED** [review]

**Review by stormi — APPROVED** [review]
I updated the changelog date for the imminent build.

**Comment by stormi** [comment]
Koji build (v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=38681

**Pull request merged**
